# Exception

In [1]:
def invert(x):
    try:
        ans = 1/x
    except Exception as err:
        pass
    else:
        return ans
    
    
li = [1, 2, 0, [1, 3, 4], 'abc']
for data in li:
    res = invert(data)
    if res != None:
        print('1/',data,'=',res)
    else:
        print('1/',data,'= undefined')

1/ 1 = 1.0
1/ 2 = 0.5
1/ 0 = undefined
1/ [1, 3, 4] = undefined
1/ abc = undefined


In [2]:
f1 = open('data.txt', 'w')
f1.write('one\ntwo\nthree')
f1.close()

In [3]:
f1 = open('data.txt', 'r')
cont = f1.read()
print(cont)
f1.close()

one
two
three


In [4]:
f1 = open('data.txt', 'r')
for line in f1:
    print(line, end=' ')
f1.close()

one
 two
 three 

# Numpy

In [5]:
import numpy as np
print(type(np))

<class 'module'>


In [6]:
data = 10*np.random.randn(2, 3, 4)

In [7]:
print(data)

[[[ -2.59609119 -18.80489988 -11.62663982  15.93971052]
  [ 10.9412153   -1.47801611  12.75310272 -17.04874373]
  [ 10.35837501  -1.80762766   2.31680819  16.02817195]]

 [[-13.56041186   8.80496801 -22.11885714  -7.35853102]
  [  1.99798725  -8.03457239   1.21629998  16.38192384]
  [  1.0785648   -1.51194296  -1.28976977   8.44507035]]]


In [8]:
data = np.round(10*np.random.randn(2, 3, 4))
print(data)

[[[-12.   6.  -3.   2.]
  [ 15.   8. -14.   4.]
  [  9.   2.   4.  -8.]]

 [[ -2. -14.  -7.   1.]
  [  3.  -4. -12.  -2.]
  [-12.  -2.   9.  -2.]]]


In [9]:
print(data[1])

[[ -2. -14.  -7.   1.]
 [  3.  -4. -12.  -2.]
 [-12.  -2.   9.  -2.]]


In [10]:
print(data[:,1:,:])

[[[ 15.   8. -14.   4.]
  [  9.   2.   4.  -8.]]

 [[  3.  -4. -12.  -2.]
  [-12.  -2.   9.  -2.]]]


In [11]:
print(data[:,1:,1:3])

[[[  8. -14.]
  [  2.   4.]]

 [[ -4. -12.]
  [ -2.   9.]]]


In [12]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
data = np.matrix([[1,2], [5, 6], [3,4]])
print(data)

[[1 2]
 [5 6]
 [3 4]]


In [17]:
print(data.T)

[[1 5 3]
 [2 6 4]]


In [18]:
print(np.sin(data))

[[ 0.84147098  0.90929743]
 [-0.95892427 -0.2794155 ]
 [ 0.14112001 -0.7568025 ]]


In [19]:
print(np.power(data, 2))

[[ 1  4]
 [25 36]
 [ 9 16]]


In [21]:
print(np.power(data, 0.5))

[[1.         1.41421356]
 [2.23606798 2.44948974]
 [1.73205081 2.        ]]


In [22]:
print(data.dot(data.T)) ### matrix multiplication

[[ 5 17 11]
 [17 61 39]
 [11 39 25]]
